sudo: true
language: c
services: docker
addons:
  hosts:
    - mariadb.example.com

before_install:
  - chmod +x .travis/script.sh
  - chmod +x .travis/gen-ssl.sh
  - chmod +x .travis/build/build.sh
  - chmod +x .travis/build/docker-entrypoint.sh
  - chmod 777 .travis/build/
  - export PROJ_PATH=`pwd`
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export SSLCERT=$PROJ_PATH/tmp
  - export CONNECTOR_C_VERSION=v_2.3.3

matrix:
  allow_failures:
    - env: DB=build
  include:
    - env: DB=build
#    - env: DB=mysql:5.5
#    - env: DB=mysql:5.6
#    - env: DB=mysql:5.7
    - env: DB=mariadb:5.5
    - env: DB=mariadb:10.0
    - env: DB=mariadb:10.1
    - env: DB=mariadb:10.2
    - env: DB=mariadb:10.3
#    - env: DB=mariadb:10.2 PACKET=8M MAXSCALE_VERSION=2.1.8

script:
  - if [ "$DB" = "build" ] ; then .travis/build/build.sh; fi
  - if [ "$DB" = "build" ] ; then docker build -t build:latest --label build .travis/build/; fi
  - .travis/script.sh
